
# Permalinks

permalink:      /:year-:month-:day/:title

paginate:       5



# Site settings

title:          Hyeji's BLOG

description:    "Record what I learned here."

baseurl:        ""

url:            "https://hyejiyunw.github.io"



# Google Analytics

google_analytics: UA—XXXXXXXX-X



# Author

author:

  name:         Hyeji Yun

  url:          https://hyejiyunw.github.io

  email:        hyejiyunw@gmail.com

  github:       hyejiyunw



# Build settings

markdown:       kramdown

include:

  - _pages



# Assets

sass:

  sass_dir:     _sass

  style:        compressed



# Gems

plugins:

  - jekyll-feed

  - jekyll-paginate

  - jekyll-seo-tag

  - jemoji #Uncomment this to allow emoji in your post







# Excludes

exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]



# Disqus (Set to your disqus id)
disqus:     hyejiyun
